movieapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
app_name = 'movieapp'
urlpatterns = [
  path('',views.index,name='index'),
  path('movie/<int:movie_id>/',views.detail,name='detail'),
  path('add/',views.add_movie,name='add_movie'),
  path('update/<int:id>/',views.update,name='update'),
  path('delete/<int:id>/',views.delete,name='delete')

]

movies/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from movies import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieapp/forms.py
from django import  forms
from .models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,'details.html',{'movie':movie})


def add_movie(request):
    if request.method=='POST':
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        move = Movie(name=name,desc=desc,year=year,img=img)
        move.save()

    return render(request,'add.html')

def update(request,id):
    movie = Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type ="text" name="name" placeholder="enter movie name"><br>
    <br>

    <input type ="text" name="desc" placeholder="enter movie desc"><br>
    <br>

    <input type ="text" name="year" placeholder="enter movie year"><br>
    <br>
    <input type ="file" name="img">
    <input type ="submit">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}

    Are You Want To Delete This Movie
    <input type="submit">

</form>

{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row" >
        <div class="col-md -6">
            <img src="{{movie.img.url}}"width="505" height="560">
        </div>
  <div class="col-md-6">
    <h6>{{movie.name}}</h6>
    <br>
    <h6>{{movie.desc}}</h6>
    <br>
    <h6>{{movie.year}}</h6>
    <br>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}" > update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}"> Delete</a>
  </div>
    </div>

{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class=" row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 15rem;">
  <img class="card-img-top" src="{{i.img.url}}"width="100" height="180" alt="Card image cap">
  <div class="card-body">
    <h5><a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">{{i.name}}</a></h5>
    <p class="card-text">{{i.desc}}</p>

  </div>
</div>

        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}